name: Test and Build

on:
  push:
    tags:
      - **

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true

    - name: Test
      run: go test -v ./...

    - name: Build
      run: go build -o notes

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: notes
